Repository Mi-Ss-A/missa-front, pull requests merged in 2024-12, with the labels that each got.

#72 feat: 포트폴리오 리스트 기능 추가 (#71)
  src/pages/LoginPage.js
  src/pages/PortfolioPage.js
  src/pages/PreferencePage.js
  src/router/root.js
Labels: feat

#74 refactor: favicon and chat (#73)
  public/favicon.ico
  public/icon.png
  public/index.html
  public/logo192.png
  public/logo512.png
  src/components/chat/ChatMessage.js
  src/pages/ChatHistoryDetail.js
  src/pages/HistoryPage.js
Labels: feat, refactor

#76 chore:favicon, 로고 이미지, title 수정(#75)
  public/favicon.ico
  public/icon.png
  public/index.html
Labels: refactor

#78 refactor: 각종 버그 수정 (#77)
  public/index.html
  public/user.png
  src/App.js
  src/components/chat/ChatMessage.js
  src/pages/ChatPage.js
  src/pages/PortfolioPage.js
  src/pages/PreferencePage.js
  src/util/ChatContext.js
Labels: feat, refactor

#80 feat: 추가 기능 개발 완료 (#79)
  src/App.css
  src/App.js
  src/components/chat/ChatInput.js
  src/components/login/Footer.js
  src/components/login/InputField.js
  src/components/login/LoginForm.js
  src/components/signup/SignUpButton.js
  src/components/signup/SignUpForm.js
  src/components/signup/SignUpInput.js
  src/components/signup/SignUpSelect.js
  src/pages/LoginPage.js
  src/pages/PreferencePage.js
  src/pages/SignUpPage.js
  src/router/root.js
  src/util/UserContext.js
Labels: feat, refactor

#81 bug: 기타 등등 버그 수정 (#77)
  src/components/chat/ChatInput.js
  src/components/signup/SignUpForm.js
  src/index.js
  src/pages/HistoryPage.js
  src/pages/PortfolioPage.js
Labels: bug, feat, refactor
