Repository Mi-Ss-A/missa-front, pull requests merged in 2024-11, with the labels that each got.

#6 page 4, page 5, page 6, page 7
  .gitignore
  .idea/workspace.xml
  package-lock.json
  package.json
  src/App.js
  src/components/chat/ChatInput.js
  src/components/chat/ChatMessage.js
  src/components/chat/RegenerateButton.js
  src/components/menus/BasicMenu.js
  src/components/menus/Header.js
  src/layouts/BasicLayout.js
  src/pages/ChatPage.js
  src/pages/HistoryPage.js
  src/pages/MainPage.js
  src/pages/PreferencePage.js
  src/router/root.js
Labels: feat

#7 [Feat] 로그인 뷰 틀 작성 (#2)
  package-lock.json
  src/components/button/GetStartedButton.css
  src/components/button/GetStartedButton.js
  src/components/loading/WelcomeLoading.css
  src/components/loading/WelcomeLoading.jsx
  src/components/login/Button.css
  src/components/login/Button.js
  src/components/login/Footer.css
  src/components/login/Footer.js
  src/components/login/Header.css
  src/components/login/Header.js
  src/components/login/InputField.css
  src/components/login/InputField.js
  src/components/login/LoginForm.css
  src/components/login/LoginForm.js
  src/components/login/LoginPage.css
  src/components/onboard/Description.css
  src/components/onboard/Description.js
  src/components/onboard/GetStartedButton.css
  src/components/onboard/GetStartedButton.js
  src/components/onboard/OnboardingPage.css
  src/components/onboard/WelcomeMessage.css
  src/components/onboard/WelcomeMessage.js
  src/components/onboard/WibeeLogo.css
  src/components/onboard/WibeeLogo.js
  src/layouts/LoginLayout.js
  src/pages/LoginPage.js
  src/pages/OnBoardingPage.js
  src/pages/SplashPage.js
  src/router/root.js
  src/wibee.png
Labels: feat

#13 feat: login binding (#12)
  package-lock.json
  package.json
  src/components/login/Button.js
  src/components/login/InputField.js
  src/components/login/LoginForm.js
  src/pages/LoginPage.js
Labels: feat

#15 feat: chatmessage flask 서버로 전송 & 응답 기능
  package-lock.json
  package.json
  src/components/chat/ChatInput.js
  src/components/chat/ChatMessage.js
  src/components/chat/RegenerateButton.js
  src/pages/ChatPage.js
Labels: feat

#17 feat: portfolio 로직 구현
  src/components/chat/ChatInput.js
Labels: feat

#20 feat:Front-end CICD 테스트 설정(#19)
  .dockerignore
  Dockerfile
  Jenkinsfile
Labels: feat

#23 fix:$문자 이스케이프 처리(#22)
  Jenkinsfile
Labels: bug, refactor

#24 fix:쌍따옴표 따옴표로 변경(#22)
  Jenkinsfile
Labels: bug, refactor

#21 feat: senario button innitial api 요청 연결 & css 수정
  src/components/chat/ChatInput.js
  src/pages/ChatPage.js
Labels: feat

#26 fix:credentials 토큰 명 수정 (#25)
  Jenkinsfile
Labels: bug, refactor

#28 fix:docker token재발급으로 인한 token명 변경(#27)
  Jenkinsfile
Labels: bug, refactor

#30 fix:jenkins파일 수정(#29)
  Jenkinsfile
Labels: bug, refactor

#31 fix:credentials 검증 부분에 docker registry url 추가(#29)
  Jenkinsfile
Labels: bug, refactor

#32 fix:docker withRegistry 함수에 맞게 변수 선언(#29)
  Jenkinsfile
Labels: bug, refactor

#33 fix:git credentials 호출 방식 맞게 수정(#29)
  Jenkinsfile
Labels: bug, refactor

#34 fix:argocd-config repo 브렌치 test로 수정(#29)
  Jenkinsfile
Labels: bug, refactor

#35 fix:github push url로 수정(#29)
  Jenkinsfile
Labels: bug, refactor

#38 refactor: 포트폴리오 api 기간 입력시 오류 해결
  src/components/chat/ChatInput.js
Labels: bug

#47 Feat/#43/nginx
  Dockerfile
  Jenkinsfile
  nginx.conf
Labels: feat, refactor

#50 feat:배포된 서버에서 spa 인식을 위한 nginx.conf 파일 수정 (#44)
  nginx.conf
Labels: feat, refactor

#52 refactor: 디자인 수정 + 로그아웃 연결
  src/components/login/Button.js
  src/components/login/Footer.js
  src/components/login/Header.js
  src/components/login/InputField.js
  src/components/login/LoginForm.js
  src/pages/LoginPage.js
  src/pages/PreferencePage.js
Labels: refactor

#58 Chore/#57/merge
  .idea/workspace.xml
  Dockerfile
  nginx.conf
  package.json
  src/App.js
  src/components/chat/ChatInput.js
  src/components/chat/ChatMessage.js
  src/components/chat/RegenerateButton.js
  src/components/loading/WelcomeLoading.js
  src/components/login/Footer.js
  src/components/login/LoginForm.js
  src/components/menus/BasicMenu.js
  src/components/menus/Header.js
  src/components/onboard/GetStartedButton.js
  src/layouts/BasicLayout.js
  src/pages/ChatHistoryDetail.js
  src/pages/ChatPage.js
  src/pages/HistoryPage.js
  src/pages/LoginPage.js
  src/pages/MainPage.js
  src/pages/OnBoardingPage.js
  src/pages/PreferencePage.js
  src/pages/SplashPage.js
  src/router/root.js
  src/util/axios.js
Labels: refactor

#60 refactor: chat Design 수정 (#59)
  package-lock.json
  package.json
  src/components/chat/ChatInput.js
  src/components/chat/ChatMessage.js
  src/components/chat/RegenerateButton.js
  src/components/menus/Header.js
  src/components/ui/Button.js
  src/components/ui/LoadingSpinner.js
  src/pages/ChatPage.js
  tailwind.config.js
Labels: refactor

#64 feat: 로그아웃 로직 수정 (#12)
  src/components/chat/ChatInput.js
  src/pages/PreferencePage.js
Labels: feat, refactor
